# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  r: $(Date:yyyyMMdd)
  b: $(Rev:.r)
  c: $(Build.SourceVersion)
  BUILD_NUMBER: $r$b.$c
  README: /home/vsts/work/_temp/readme.txt 

pool: 
  vmImage: ubuntu-16.04

steps:
  - script: sudo apt-get install -y libboost-all-dev
  - script: sudo g++ -std=c++11 -I/usr/include/boost/asio -I/usr/include/boost -o /home/vsts/work/_temp/binary.out main.cpp connection.cpp connection_manager.cpp mime_types.cpp reply.cpp request_handler.cpp request_parser.cpp server.cpp -lboost_system -lboost_thread -lpthread
 
  - script: sudo mv /home/vsts/work/_temp/binary.out /home/vsts/work/_temp/$BUILD_NUMBER.out
  
  - script: if [ ! -f $README ];
            then echo $(touch $README)
            else
            echo 
            fi

  - script: sudo echo $BUILD_NUMBER | tee -a $README

  - task: CopyFiles@1
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      Contents: |
       /home/vsts/work/_temp/*.out
       /home/vsts/work/_temp/readme.txt
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
