# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  r: Release
  b: variables['Build.BuildNumber']
  c: variables['Build.SourceVersion']
  BUILD_NUMBER: $r.$b.$c
  README: ./readme.txt 

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - bash: sudo apt-get install -y libboost-all-dev
  - bash: sudo g++ -std=c++11 -I/usr/include/boost/asio -I/usr/include/boost -o binary.out main.cpp connection.cpp connection_manager.cpp mime_types.cpp reply.cpp request_handler.cpp request_parser.cpp server.cpp -lboost_system -lboost_thread -lpthread

  - bash: sudo mv binary.out $BUILD_NUMBER.out
  

  - bash: sudo echo $BUILD_NUMBER | tee -a $README